apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: prometheus-calico
  name: prometheus-calico
  namespace: kube-system
subsets:
- addresses:
  - ip: 172.17.0.1
  - ip: 172.17.0.2
  ports:
  - name: http-metrics
    port: 9091
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-calico
  name: prometheus-calico
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    k8s-app: prometheus-calico
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: calico
  namespace: kube-system
spec:
  endpoints:
  - path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: prometheus-calico
---
